---
# tasks file for ansible-role-sonarr

- name: Adding key EBFF6B99D9B78493 (sonarr)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EBFF6B99D9B78493

- name: Adding repository http://apt.sonarr.tv/
  apt_repository:
    repo: deb http://apt.sonarr.tv/ master main
    state: present

- name: Adding key 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF (mono)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Adding repository http://download.mono-project.com/repo/ubuntu
  apt_repository:
    repo: "deb http://download.mono-project.com/repo/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: Installing packages 
  package:
     name: "{{ item }}"
     state: present
  with_items:
     - mono-devel
     - nzbdrone

- name: Add user "{{sonarr_user}}"
  user:
    name: "{{sonarr_user}}"

- name: Configuring Autostart 
  template:
    src: templates/sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    owner: root
    group: root
    mode: 0644

- name: Enable Service
  systemd:
    name: sonarr
    enabled: yes
    masked: no

- name: Start Sonarr
  systemd: state=started name=sonarr

- name: Ensures /home/{{sonarr_user}}/.config/NzbDrone/ dir exists
  file: path=/home/{{sonarr_user}}/.config/NzbDrone/ state=directory

- name: Configuring Sonarr config.xml 
  template:
    src: templates/config.xml.j2
    dest: /home/{{sonarr_user}}/.config/NzbDrone/config.xml
    owner: "{{sonarr_user}}"
    group: "{{sonarr_group}}"
  notify: restart sonarr
